# app/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: demo-dev 
  labels:
    app: nodejs-app
spec:
  selector:
    app: nodejs-app
    version: blue 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 
  type: LoadBalancer 